name: CI pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Amazon ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.0.1
        with:
          mask-password: 'true'

      - name: Build, tag, and push docker image to Amazon ECR
        id: docker-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: pipeline
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Amazon ECS Render Task Definition Action for GitHub Actions
        id: create-task
        uses: aws-actions/amazon-ecs-render-task-definition@v1.7.4
         with:
          task-definition: .aws/task-definition.json
          container-name: node-container
          image: ${{steps.docker-image.outputs.image}}

      - name: Amazon ECS "Deploy Task Definition" Action for GitHub Actions
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2.3.3
        with:
          task-definition: ${{steps.create-task.outputs.task-definition}}
          service: pipeline-task-service-563uo5vx
          cluster: hospitable-turtle-h91cyn
          wait-for-service-stabilit: true